---
#
# vagrant.yml
#
- hosts: vagrant
  become: yes
  tasks:
    # common
    - name: install modules
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - fish
          - git
          - tig
          - vim

    - name: change default shell
      user:
        name: vagrant
        shell: /usr/bin/fish

    - name: make dein.vim directory
      file:
        path: /home/.vim/dein/repos/github.com/Shougo/dein.vim
        owner: vagrant
        state: directory
        recurse: yes

    - name: make vim.dein directory
      file:
        dest: "/home/vagrant/.vim/dein/repos/github.com/Shougo/dein.vim"
        owner: vagrant
        state: directory
        recurse: yes

    - name: install vim.dein
      git:
        repo: "https://github.com/Shougo/dein.vim.git"
        dest: /home/vagrant/.vim/dein/repos/github.com/Shougo/dein.vim

    - name: dein.vim
      get_url:
        url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
        dest: /home/vagrant/installer.sh
        owner: vagrant

    - name: dein.vim
      file:
        path: /home/vagrant/.cache/dein
        owner: vagrant
        state: directory
        recurse: yes

    - name: dein.vim
      shell:
        cmd: bash /home/vagrant/installer.sh /home/vagrant/.cache/dein
      become_user: vagrant

    - name: make directory
      file:
        path: "/home/vagrant/dev/src/github.com/rusagedougawa/dotfiles"
        owner: vagrant
        state: directory
        recurse: yes

    - name: install dot files
      git:
        repo: "https://github.com/rusagedougawa/dotfiles.git"
        dest: /home/vagrant/dev/src/github.com/rusagedougawa/dotfiles

    - name: link dotfiles
      file:
        src: "/home/vagrant/dev/src/github.com/rusagedougawa/dotfiles/{{ item.src }}"
        dest: "/home/vagrant/{{ item.dest }}"
        state: link
      with_items:
        - { src: ".vimrc", dest: ".vimrc" }
